In [84]:
import numpy as np
import corex as ce
import pandas as pd

In [85]:
X=pd.read_csv('LUADGeneTableDE.csv',index_col=0)

layer1 = ce.Corex(n_hidden=20,dim_hidden=3, marginal_description='gaussian', smooth_marginals=True, verbose=1,ram=4)  
layer2 = ce.Corex(n_hidden=10)
layer3 = ce.Corex(n_hidden=5)
Y1 = layer1.fit_transform(X)
Y2 = layer2.fit_transform(Y1)
Y3 = layer3.fit_transform(Y2)


corex, rep size: 20 3
Marginal description:  gaussian
[ 0.254  0.03   0.129  1.146  0.193  0.087  0.16   0.104  0.255  0.085  0.06   0.055  0.091  0.166  0.019  0.284  0.023  0.208  0.157  0.216]
[  8.609  -0.012   1.788  20.669   0.241   2.755  -0.029   0.809   6.019   0.02   -0.007   0.734   5.641  10.331   0.377   1.372   0.05    2.431   0.55    0.067]
[  8.115   0.      4.059   8.73    2.754  22.529   0.287   0.362   2.578   0.412   2.199   7.241   6.078   1.473   5.307   0.873   6.612   3.396   1.073   0.257]
[  3.858   0.02    3.612  11.106   4.195  25.36    1.347   3.456   5.472   2.877   3.829   3.051   3.837   2.806   4.978   2.494  10.637   6.747   1.952   0.506]
[  2.734   0.889   3.684  10.341   3.77   28.416   1.688   5.026   6.678   1.891   4.265   2.29    3.897   3.216   6.609   3.073  11.03    7.581   2.442   0.914]
[  1.217   2.305   3.375   9.273   3.312  29.036   1.616   6.367   8.003   1.546   5.448   2.084   3.811   4.977   7.17    3.776  11.02    7.226   2.738   1

[  1.926   2.972   2.672   6.303   1.298  16.801   0.288   5.16    8.521   6.752   4.407   3.385   2.869   7.323   6.578  10.136   5.972   3.708  15.68    7.29 ]
[  1.953   2.83    2.643   5.644   1.278  12.338   0.096   5.036   8.207   6.221   4.362   3.34    2.776   6.907   6.563   8.462   6.026   3.564  21.256   8.657]
[  1.863   2.434   2.68    5.449   1.035  10.452   0.122   4.775   7.8     6.567   4.273   3.209   2.857   6.74    6.319   7.672   5.532   3.467  24.192   9.135]
[  1.96    2.477   2.656   5.442   0.922  11.417   0.124   4.823   7.81    6.157   4.148   3.268   2.977   7.019   6.309   7.46    5.688   3.441  24.196   8.884]
[  1.817   2.577   2.638   5.33    0.853  11.468   0.147   5.289   7.748   6.334   4.216   3.38    2.949   7.342   6.457   6.587   5.937   3.713  24.132   8.8  ]
[  1.698   2.48    2.637   5.19    0.84   11.556   0.149   5.276   7.76    6.524   4.227   3.346   3.271   7.326   6.436   6.172   5.754   3.648  24.436   8.945]
[  1.721   2.574   2.668   4

In [99]:
corexGroup1=pd.DataFrame(data=layer1.clusters, index=X.transpose().index)
corexGroup1.columns=['corexGroup']

mI=[]
for ii in range(0, len(layer1.clusters)):
    mI.append(layer1.mis[layer1.clusters[ii],ii])
#len(mI)
corexGroup1['mI']=mI

corexGroup2=[]
for ii in range(0, len(layer1.clusters)):
    corexGroup2.append(layer2.clusters[layer1.clusters[ii]])
corexGroup1['corexGroup2']=corexGroup2

corexGroup1.to_csv('corexGroup1.csv')

mutualInformation1=pd.DataFrame(data=mI, index=X.transpose().index)
mutualInformation1.columns=['mI']
mutualInformation1.to_csv('mutualInformation1.csv')

totalCorrelation1=pd.DataFrame(data=layer1.tcs, index=list(range(len(layer1.tcs))))
totalCorrelation1.columns=['totalCorrelation']
totalCorrelation1.to_csv('totalCorrelation1.csv')

labels1=pd.DataFrame(data=layer1.labels,index=X.index)
labels1
labels1.to_csv('labels1.csv')

In [87]:
mI2=[]
for ii in range(0, len(layer2.clusters)):
    mI2.append(layer2.mis[layer2.clusters[ii],ii])
len(mI2)

corexGroup2=pd.DataFrame(data=layer2.clusters,index=np.array(range(0, layer1.labels[0].size)))
corexGroup2.columns=['corexGroup']
corexGroup2['mI']=mI2
corexGroup2.to_csv('corexGroup2.csv')

In [73]:
layer1.clusters # Each variable/column is associated with one Y_j
#layer1.labels # Labels for each sample for Y_0
#layer1.tcs # TC(X;Y_j) (all info measures reported in nats)
layer1.labels.shape

(533, 20)

In [64]:
layer1.p_y_given_x

array([[[ 0.999,  0.001,  0.   ],
        [ 0.999,  0.001,  0.   ],
        [ 0.   ,  0.   ,  1.   ],
        ..., 
        [ 0.   ,  0.   ,  1.   ],
        [ 1.   ,  0.   ,  0.   ],
        [ 0.993,  0.   ,  0.007]],

       [[ 0.137,  0.   ,  0.863],
        [ 0.689,  0.   ,  0.311],
        [ 0.   ,  0.007,  0.993],
        ..., 
        [ 0.   ,  0.   ,  1.   ],
        [ 0.989,  0.011,  0.   ],
        [ 1.   ,  0.   ,  0.   ]],

       [[ 0.   ,  0.   ,  1.   ],
        [ 0.129,  0.871,  0.   ],
        [ 0.   ,  1.   ,  0.   ],
        ..., 
        [ 0.999,  0.   ,  0.001],
        [ 0.028,  0.972,  0.   ],
        [ 0.291,  0.   ,  0.709]],

       ..., 
       [[ 0.001,  0.999,  0.   ],
        [ 1.   ,  0.   ,  0.   ],
        [ 0.   ,  0.005,  0.995],
        ..., 
        [ 0.001,  0.879,  0.12 ],
        [ 1.   ,  0.   ,  0.   ],
        [ 0.   ,  0.067,  0.933]],

       [[ 0.06 ,  0.011,  0.929],
        [ 0.098,  0.   ,  0.902],
        [ 0.004,  0.996,  0.001],
     

In [65]:
layer1.alpha

array([[[ 0.   ],
        [ 0.   ],
        [ 0.   ],
        ..., 
        [ 1.   ],
        [ 0.   ],
        [ 0.005]],

       [[ 0.   ],
        [ 0.   ],
        [ 0.   ],
        ..., 
        [ 0.014],
        [ 0.   ],
        [ 0.016]],

       [[ 0.102],
        [ 0.   ],
        [ 0.006],
        ..., 
        [ 0.005],
        [ 0.048],
        [ 0.009]],

       ..., 
       [[ 0.   ],
        [ 0.005],
        [ 0.079],
        ..., 
        [ 0.   ],
        [ 0.16 ],
        [ 0.   ]],

       [[ 0.032],
        [ 0.051],
        [ 0.269],
        ..., 
        [ 0.005],
        [ 0.   ],
        [ 0.   ]],

       [[ 0.   ],
        [ 0.15 ],
        [ 0.026],
        ..., 
        [ 0.   ],
        [ 0.008],
        [ 0.019]]])

In [66]:
#how much each gene is in each latent factor
layer1.mis

array([[ 0.01 , -0.   ,  0.01 , ...,  0.624,  0.   ,  0.   ],
       [-0.   ,  0.035,  0.   , ..., -0.   ,  0.   , -0.   ],
       [ 0.152, -0.   ,  0.012, ..., -0.   , -0.   , -0.   ],
       ..., 
       [ 0.013, -0.   ,  0.062, ...,  0.   , -0.   ,  0.   ],
       [ 0.033, -0.   ,  0.006, ...,  0.   ,  0.023, -0.   ],
       [ 0.014,  0.026,  0.012, ..., -0.   ,  0.021, -0.   ]])

In [51]:
help()


Welcome to Python 3.6's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at http://docs.python.org/3.6/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".


You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


In [60]:
help(ce)

Help on module corex:

NAME
    corex - Maximally Informative Representations using CORrelation EXplanation

DESCRIPTION
    Main ideas first described in:
    Greg Ver Steeg and Aram Galstyan. "Maximally Informative
    Hierarchical Representations of High-Dimensional Data"
    AISTATS, 2015. arXiv preprint(arXiv:1410.7404.)
    
    The Bayesian smoothing option is described in:
    Pepke and Ver Steeg, Comprehensive discovery of subsample gene expression components
    by information explanation: therapeutic implications in cancer. BMC Medical Genomics, 2017.
    
    Code below written by: Greg Ver Steeg (gregv@isi.edu)
    
    License: Apache V2

CLASSES
    builtins.object
        Corex
    
    class Corex(builtins.object)
     |  Correlation Explanation
     |  
     |  A method to learn a hierarchy of successively more abstract
     |  representations of complex data that are maximally
     |  informative about the data. This method is unsupervised,
     |  requires no assump